---
name: kblocks
version: 17.04.3
summary: Falling Blocks Game
description: KBlocks is the classic falling blocks game. The idea is to stack the
    falling blocks to create horizontal lines without any gaps. When a line is completed
    it is removed, and more space is available in the play area. When there is not
    enough space for blocks to fall, the game is over.
confinement: strict
grade: stable
apps:
    kblocks:
        command: kf5-launch kblocks
        plugs:
        - kde-frameworks-5-plug
        - home
        - x11
        - opengl
        - network
        - network-bind
        - unity7
        - pulseaudio
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.kblocks
        bus: session
plugs:
    kde-frameworks-5-plug:
        content: kde-frameworks-5-all
        interface: content
        default-provider: kde-frameworks-5
        target: kf5
parts:
    kblocks:
        after: [kde-frameworks-5-dev, kde-frameworks-5-env]
        plugin: cmake
        build-packages:
        - kdoctools-dev
        - libkf5kdegames-dev
        - libkf5kdelibs4support-dev
        - libphonon4qt5-dev
        - libphonon4qt5experimental-dev
        - libpulse0
        source: https://download.kde.org/stable/applications/17.04.3/src/kblocks-17.04.3.tar.xz
        configflags:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
